---
- hosts: localenv
  roles:
    - {role: common}
    - {role: postgres}
    - {role: server, local_code_base: "{{home_dir}}/new_order", remote_code_base: "https://github.com/sjkyspa/product_new.git"}