---
- name: pull code base
  git: repo={{remote_code_base}} dest={{local_code_base}} update=yes

- name: install gems for app
  gem: name={{item}} state=present
  sudo_user: vagrant
  with_items:
    - bundler
- name: bundle install all dependencies
  sudo_user: vagrant
  command: bundle install chdir={{local_code_base}}

- name: migrate database
  sudo_user: vagrant
  command: rake db:migrate chdir={{local_code_base}}

- name: start server
  sudo_user: vagrant
  shell: nohup rails server >nohup.out 2>&1 & chdir={{local_code_base}}